// JSON-LD builders (fenlon11/pmOS#685, playbook §2.1). Rules: every date and headline equals the
// visible text (jsonld.test.ts); author and publisher are always the Persistent Momentum
// Organization, never a Person, and Elle Evate (AI) never gets Person markup (Matt, 2026-10-10);
// no street address; no FAQPage or HowTo anywhere (Google retired both rich results in 2026).
import type { Article, AuthorEntry } from '../content/index.ts';
import { SITE_EMAIL, SITE_LEGAL_NAME, SITE_NAME, SITE_URL, absoluteUrl } from '../site.ts';

const context = 'https://schema.org';
export const ORG_ID = `${SITE_URL}/#organization`;

// Verified profiles only. None exist of record yet (docs/architecture/accounts-of-record.md,
// 2026-10-10); never add one that isn't PM-owned.
export const ORG_SAME_AS: string[] = [];

const orgRef = { '@type': 'Organization', '@id': ORG_ID, name: SITE_NAME, url: SITE_URL };

export function organizationJsonLd() {
  return {
    '@context': context,
    '@type': 'Organization',
    '@id': ORG_ID,
    name: SITE_NAME,
    legalName: SITE_LEGAL_NAME,
    url: SITE_URL,
    email: SITE_EMAIL,
    logo: { '@type': 'ImageObject', url: absoluteUrl('/logo.png'), width: 762, height: 720 },
    ...(ORG_SAME_AS.length > 0 ? { sameAs: ORG_SAME_AS } : {}),
  };
}

// The per-article image generated by next/og (opengraph-image.tsx beside each article route).
export const articleImageUrl = (article: Pick<Article, 'href'>) => absoluteUrl(`${article.href}/opengraph-image`);

export function articleJsonLd(article: Article) {
  const url = absoluteUrl(article.href);
  return {
    '@context': context,
    '@type': article.type === 'news' ? 'NewsArticle' : 'BlogPosting',
    '@id': `${url}#article`,
    mainEntityOfPage: url,
    url,
    headline: article.title,
    description: article.description,
    image: [articleImageUrl(article), ...(article.heroImage ? [absoluteUrl(article.heroImage)] : [])],
    datePublished: article.publishedAt,
    dateModified: article.updatedAt,
    author: orgRef,
    publisher: orgRef,
    keywords: article.tags,
    isAccessibleForFree: true,
  };
}

export function breadcrumbJsonLd(article: Article) {
  const section = article.type === 'news' ? { name: 'News', path: '/news' } : { name: 'Guides', path: '/guides' };
  const items = [
    { name: 'Home', path: '/' },
    section,
    { name: article.title, path: article.href },
  ];
  return {
    '@context': context,
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: absoluteUrl(item.path),
    })),
  };
}

// ProfilePage only for an Organization author. An AI author gets no profile markup at all, and
// no author is ever a Person.
export function profilePageJsonLd(author: AuthorEntry) {
  if (author.kind !== 'organization') return null;
  return {
    '@context': context,
    '@type': 'ProfilePage',
    url: absoluteUrl(author.href),
    mainEntity: { ...orgRef, description: author.description },
  };
}

// Serialise for a <script type="application/ld+json">; escaping `<` keeps a `</script>` in any
// string from closing the tag (Next.js JSON-LD guide).
export function serializeJsonLd(data: object) {
  return JSON.stringify(data).replace(/</g, '\\u003c');
}
