// ===== SECRETS REGISTRY =====
// Inventory of all env vars across projects. NO actual values stored here.
// Values live in .env.local on matts-macbook-pro only.

export type KeyStatus = 'set' | 'missing' | 'expired' | 'unknown';

export interface SecretEntry {
  id: string;
  service: string;
  keyName: string;
  project: string;       // Which .env.local file (e.g., "rabbit-golf", "persistent-momentum")
  envFile: string;        // Full path on disk
  purpose: string;
  required: boolean;
  status: KeyStatus;
  lastVerified?: string;  // ISO date
  notes?: string;
  docsUrl?: string;       // Where to get/rotate the key
}

export interface ServiceGroup {
  service: string;
  icon: string;
  keys: SecretEntry[];
}

// Master registry — update this when adding new keys
export const secretsRegistry: SecretEntry[] = [
  // === persistent_momentum (old dir) ===
  {
    id: '1',
    service: 'Supabase',
    keyName: 'NEXT_PUBLIC_SUPABASE_URL',
    project: 'persistent_momentum',
    envFile: '~/Projects/persistent_momentum/.env.local',
    purpose: 'Supabase project URL for legacy PM app',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '2',
    service: 'Supabase',
    keyName: 'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    project: 'persistent_momentum',
    envFile: '~/Projects/persistent_momentum/.env.local',
    purpose: 'Supabase anon key for client-side access',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '3',
    service: 'Supabase',
    keyName: 'SUPABASE_SERVICE_ROLE_KEY',
    project: 'persistent_momentum',
    envFile: '~/Projects/persistent_momentum/.env.local',
    purpose: 'Supabase service role for server-side operations (bypasses RLS)',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '4',
    service: 'Resend',
    keyName: 'RESEND_API_KEY',
    project: 'persistent_momentum',
    envFile: '~/Projects/persistent_momentum/.env.local',
    purpose: 'Transactional email via Resend',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '5',
    service: 'Config',
    keyName: 'NOTIFICATION_EMAIL',
    project: 'persistent_momentum',
    envFile: '~/Projects/persistent_momentum/.env.local',
    purpose: 'Email address for system notifications',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },

  // === persistent-momentum/website (NEW site) — FILE MISSING ===
  {
    id: '6',
    service: 'Supabase',
    keyName: 'NEXT_PUBLIC_SUPABASE_URL',
    project: 'persistent-momentum/website',
    envFile: '~/Projects/persistent-momentum/website/.env.local',
    purpose: 'Supabase project URL for PM dashboard',
    required: true,
    status: 'missing',
    lastVerified: '2025-02-28',
    notes: 'env file missing — needs creation',
  },
  {
    id: '7',
    service: 'Supabase',
    keyName: 'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    project: 'persistent-momentum/website',
    envFile: '~/Projects/persistent-momentum/website/.env.local',
    purpose: 'Supabase anon key for client-side access',
    required: true,
    status: 'missing',
    lastVerified: '2025-02-28',
    notes: 'env file missing — needs creation',
  },
  {
    id: '8',
    service: 'Supabase',
    keyName: 'SUPABASE_SERVICE_ROLE_KEY',
    project: 'persistent-momentum/website',
    envFile: '~/Projects/persistent-momentum/website/.env.local',
    purpose: 'Supabase service role for server-side operations (bypasses RLS)',
    required: true,
    status: 'missing',
    lastVerified: '2025-02-28',
    notes: 'env file missing — needs creation',
  },
  {
    id: '9',
    service: 'Config',
    keyName: 'DASHBOARD_PIN',
    project: 'persistent-momentum/website',
    envFile: '~/Projects/persistent-momentum/website/.env.local',
    purpose: 'PIN for dashboard authentication',
    required: true,
    status: 'missing',
    lastVerified: '2025-02-28',
    notes: 'env file missing — needs creation',
  },

  // === rabbit-golf-mixer ===
  {
    id: '10',
    service: 'Config',
    keyName: 'PORT',
    project: 'rabbit-golf-mixer',
    envFile: '~/Projects/rabbit-golf-mixer/.env.local',
    purpose: 'Server port for local development',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '11',
    service: 'Cloudflare R2',
    keyName: 'R2_ACCOUNT_ID',
    project: 'rabbit-golf-mixer',
    envFile: '~/Projects/rabbit-golf-mixer/.env.local',
    purpose: 'Cloudflare account ID for R2 storage',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '12',
    service: 'Cloudflare R2',
    keyName: 'R2_ACCESS_KEY_ID',
    project: 'rabbit-golf-mixer',
    envFile: '~/Projects/rabbit-golf-mixer/.env.local',
    purpose: 'R2 S3-compatible access key ID',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '13',
    service: 'Cloudflare R2',
    keyName: 'R2_SECRET_ACCESS_KEY',
    project: 'rabbit-golf-mixer',
    envFile: '~/Projects/rabbit-golf-mixer/.env.local',
    purpose: 'R2 S3-compatible secret access key',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '14',
    service: 'Cloudflare R2',
    keyName: 'R2_BUCKET',
    project: 'rabbit-golf-mixer',
    envFile: '~/Projects/rabbit-golf-mixer/.env.local',
    purpose: 'R2 bucket name for asset storage',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '15',
    service: 'Cloudflare R2',
    keyName: 'R2_PUBLIC_URL',
    project: 'rabbit-golf-mixer',
    envFile: '~/Projects/rabbit-golf-mixer/.env.local',
    purpose: 'Public CDN URL for R2 bucket assets',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },

  // === recruiterflow ===
  {
    id: '16',
    service: 'Supabase',
    keyName: 'NEXT_PUBLIC_SUPABASE_URL',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Supabase project URL for RecruiterFlow',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '17',
    service: 'Supabase',
    keyName: 'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Supabase anon key for client-side access',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '18',
    service: 'Supabase',
    keyName: 'SUPABASE_SERVICE_ROLE_KEY',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Supabase service role for server-side operations (bypasses RLS)',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '19',
    service: 'Anthropic',
    keyName: 'ANTHROPIC_API_KEY',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Claude API key for AI-powered interview prep',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '20',
    service: 'ElevenLabs',
    keyName: 'ELEVENLABS_API_KEY',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'ElevenLabs API key for voice synthesis',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '21',
    service: 'ElevenLabs',
    keyName: 'ELEVENLABS_VOICE_ID',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Selected voice ID for interview simulations',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '22',
    service: 'Cloudflare R2',
    keyName: 'R2_ACCOUNT_ID',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Cloudflare account ID for R2 storage',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '23',
    service: 'Cloudflare R2',
    keyName: 'R2_ACCESS_KEY_ID',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'R2 S3-compatible access key ID',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '24',
    service: 'Cloudflare R2',
    keyName: 'R2_SECRET_ACCESS_KEY',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'R2 S3-compatible secret access key',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '25',
    service: 'Cloudflare R2',
    keyName: 'R2_BUCKET_NAME',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'R2 bucket name for recording storage',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '26',
    service: 'Cloudflare R2',
    keyName: 'R2_PUBLIC_URL',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Public CDN URL for R2 bucket assets',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '27',
    service: 'Stripe',
    keyName: 'STRIPE_SECRET_KEY',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Stripe secret key for server-side payment processing',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '28',
    service: 'Stripe',
    keyName: 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Stripe publishable key for client-side checkout',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '29',
    service: 'Stripe',
    keyName: 'STRIPE_WEBHOOK_SECRET',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Stripe webhook signature verification secret',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '30',
    service: 'Stripe',
    keyName: 'STRIPE_PRICE_STARTER',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Stripe price ID for Starter tier',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '31',
    service: 'Stripe',
    keyName: 'STRIPE_PRICE_PRO',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Stripe price ID for Pro tier',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '32',
    service: 'Stripe',
    keyName: 'STRIPE_PRICE_AGENCY',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Stripe price ID for Agency tier',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '33',
    service: 'Resend',
    keyName: 'RESEND_API_KEY',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Transactional email via Resend',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '34',
    service: 'Config',
    keyName: 'NEXT_PUBLIC_APP_URL',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Public app URL for OAuth redirects and links',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '35',
    service: 'Config',
    keyName: 'PIPELINE_SECRET',
    project: 'recruiterflow',
    envFile: '~/Projects/recruiterflow/.env.local',
    purpose: 'Secret for pipeline webhook authentication',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },

  // === strata ===
  {
    id: '36',
    service: 'Follow Up Boss',
    keyName: 'FUB_API_KEY',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Follow Up Boss API key for CRM integration',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '37',
    service: 'Follow Up Boss',
    keyName: 'FUB_SYSTEM_NAME',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'FUB system integration identifier',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '38',
    service: 'Follow Up Boss',
    keyName: 'FUB_SYSTEM_KEY',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'FUB system integration key',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '39',
    service: 'Sisu',
    keyName: 'SISU_API_KEY',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Sisu API key for transaction analytics',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '40',
    service: 'Sisu',
    keyName: 'SISU_TEAM_ID',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Sisu team identifier for data scoping',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '41',
    service: 'Dotloop',
    keyName: 'DOTLOOP_CLIENT_ID',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Dotloop OAuth client ID for transaction management',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '42',
    service: 'Dotloop',
    keyName: 'DOTLOOP_CLIENT_SECRET',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Dotloop OAuth client secret',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '43',
    service: 'Dotloop',
    keyName: 'DOTLOOP_ACCESS_TOKEN',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Dotloop access token for API calls',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '44',
    service: 'Slack',
    keyName: 'SLACK_BOT_TOKEN',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Slack bot token for workspace notifications',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '45',
    service: 'Slack',
    keyName: 'SLACK_SIGNING_SECRET',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Slack request signature verification',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '46',
    service: 'Slack',
    keyName: 'SLACK_WORKSPACE_ID',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Slack workspace ID for team scoping',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '47',
    service: 'Google Cloud',
    keyName: 'GOOGLE_SERVICE_ACCOUNT_EMAIL',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'GCP service account email for API auth',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '48',
    service: 'Google Cloud',
    keyName: 'GOOGLE_SERVICE_ACCOUNT_KEY_PATH',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Path to GCP service account JSON key file',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '49',
    service: 'Google Cloud',
    keyName: 'GOOGLE_ADMIN_EMAIL',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Google Workspace admin email for domain-wide delegation',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '50',
    service: 'Google Cloud',
    keyName: 'GOOGLE_WORKSPACE_DOMAIN',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Google Workspace domain for directory operations',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '51',
    service: 'Google Cloud',
    keyName: 'GCP_PROJECT_ID',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'GCP project ID for API billing and scoping',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '52',
    service: 'Google BigQuery',
    keyName: 'BIGQUERY_DATASET',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'BigQuery dataset name for analytics data warehouse',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '53',
    service: 'Google Ads',
    keyName: 'GOOGLE_ADS_CUSTOMER_ID',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Google Ads customer ID for ad spend tracking',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '54',
    service: 'Google Ads',
    keyName: 'GOOGLE_ADS_DEVELOPER_TOKEN',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Google Ads API developer token',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '55',
    service: 'Fello',
    keyName: 'FELLO_API_KEY',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Fello API key for home valuation widgets',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '56',
    service: 'Fello',
    keyName: 'FELLO_ACCOUNT_ID',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Fello account ID for API scoping',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '57',
    service: 'Ruuster',
    keyName: 'RUUSTER_API_KEY',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Ruuster API key for agent routing platform',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '58',
    service: 'Speculo',
    keyName: 'SPECULO_API_KEY',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Speculo API key for market intelligence',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '59',
    service: 'Zillow',
    keyName: 'ZILLOW_PARTNER_ID',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Zillow partner ID for lead integration',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '60',
    service: 'Make',
    keyName: 'MAKE_API_TOKEN',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Make.com API token for automation scenarios',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '61',
    service: 'Make',
    keyName: 'MAKE_TEAM_ID',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Make.com team ID for org scoping',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '62',
    service: 'Make',
    keyName: 'MAKE_ORG_ID',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Make.com organization ID',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '63',
    service: 'Zapier',
    keyName: 'ZAPIER_WEBHOOK_ONBOARDING',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Zapier webhook URL for agent onboarding flow',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '64',
    service: 'Zapier',
    keyName: 'ZAPIER_WEBHOOK_ALERTS',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Zapier webhook URL for system alert notifications',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '65',
    service: 'Teachable',
    keyName: 'TEACHABLE_API_KEY',
    project: 'strata',
    envFile: '~/Projects/strata/.env.local',
    purpose: 'Teachable API key for training course platform',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },

  // === desktop-mcp-server ===
  {
    id: '66',
    service: 'Desktop MCP',
    keyName: 'MCP_AUTH_TOKEN',
    project: 'desktop-mcp-server',
    envFile: '~/Projects/desktop-mcp-server/.env.local',
    purpose: 'Auth token for Desktop MCP server access',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '67',
    service: 'Config',
    keyName: 'PORT',
    project: 'desktop-mcp-server',
    envFile: '~/Projects/desktop-mcp-server/.env.local',
    purpose: 'Server port for MCP server',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
  {
    id: '68',
    service: 'Config',
    keyName: 'ENFORCE_IP_ALLOWLIST',
    project: 'desktop-mcp-server',
    envFile: '~/Projects/desktop-mcp-server/.env.local',
    purpose: 'Toggle IP allowlist enforcement for security',
    required: true,
    status: 'set',
    lastVerified: '2025-02-28',
  },
];

// Group by service for display
export function groupByService(entries: SecretEntry[]): ServiceGroup[] {
  const serviceIcons: Record<string, string> = {
    'Supabase': '⚡',
    'Cloudflare R2': '☁️',
    'Stripe': '💳',
    'Resend': '📧',
    'Anthropic': '🤖',
    'ElevenLabs': '🔊',
    'Google Cloud': '🔍',
    'Google BigQuery': '🔍',
    'Google Ads': '🔍',
    'Slack': '💬',
    'Follow Up Boss': '📱',
    'Sisu': '📊',
    'Dotloop': '🔄',
    'Fello': '🏠',
    'Ruuster': '🏠',
    'Speculo': '🏠',
    'Zillow': '🏠',
    'Make': '⚙️',
    'Zapier': '⚡',
    'Teachable': '📚',
    'Desktop MCP': '🖥️',
    'Config': '⚙️',
  };

  const grouped = new Map<string, SecretEntry[]>();
  for (const entry of entries) {
    const existing = grouped.get(entry.service) || [];
    existing.push(entry);
    grouped.set(entry.service, existing);
  }

  return Array.from(grouped.entries()).map(([service, keys]) => ({
    service,
    icon: serviceIcons[service] || '🔑',
    keys,
  }));
}

// Stats
export function getRegistryStats(entries: SecretEntry[]) {
  const total = entries.length;
  const set = entries.filter(e => e.status === 'set').length;
  const missing = entries.filter(e => e.status === 'missing').length;
  const unknown = entries.filter(e => e.status === 'unknown').length;
  const expired = entries.filter(e => e.status === 'expired').length;
  const projects = [...new Set(entries.map(e => e.project))].length;
  const services = [...new Set(entries.map(e => e.service))].length;
  return { total, set, missing, unknown, expired, projects, services };
}
